config/routes.rb
HumanResources::Application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'pages#index', as: :home

  get "pages/about"
  get "pages/contact"

  # Make both people and teams nested resources for users
  resources :users, only: [:index, :show, :destroy] do

    resources :people do
      member do
        get :change_teams

        post 'change/:team_id', to: :add_to_team, as: :add_to_team
        delete 'change/:team_id', to: :remove_from_team, as: :remove_from_team
      end
    end

    resources :teams do
      member do
        get :change_people
        post 'change/:person_id', to: :add_person, as: :add_person
        delete 'change/:person_id', to: :remove_person, as: :remove_person
      end
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable

end

app/models/person.rb
class Person < ActiveRecord::Base
  mount_uploader :image, PersonImageUploader

  belongs_to :user

  has_many :team_memberships
  has_many :teams, through: :team_memberships

  validates :first_name,  presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  validates :phone_number, presence: true, numericality: true
  validates :email, presence: true, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ },
                    uniqueness: { case_sensitive: false }
  validates :birth_date, presence: true

  # validates :linkedin_url, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :user

  has_many :team_memberships
  has_many :people, through: :team_memberships

  validates :name, presence: true
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  belongs_to :team
  belongs_to :person
  
  validates_uniqueness_of :person_id, :scope => :team_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :teams, :dependent => :delete_all
  has_many :people, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/change_team_members.rb
module ChangeTeamMembers
  extend ActiveSupport::Concern

  def add_team_member(team_id, person_id)
    @team = Team.find(team_id)
    @person = Person.find(person_id)

    @team.people << @person
  end

  def remove_team_member(team_id, person_id)
    @team = Team.find(team_id)
    @person = Person.find(person_id)

    @team.people.delete(@person)
  end
end

app/controllers/ownership_controller.rb
class OwnershipController < ApplicationController
  before_action :require_login
  before_action -> { require_ownership params[:user_id].to_i unless admin_signed_in? }

  private
    def require_login
      unless user_signed_in? or admin_signed_in?
        flash[:alert] = "You need to sign in to access that section"
        redirect_to home_path
      end
    end

    def require_ownership(id)
      if id != current_user.id
        flash[:alert] = "You may not visit that section"
        redirect_to home_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if admin_signed_in?
      @users = User.all
    elsif user_signed_in?
      @teams = Team.where(user_id: current_user.id).includes(:people)
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/people_controller.rb
class PeopleController < OwnershipController
  include ChangeTeamMembers

  def index
    @user = User.find(params[:user_id])
    @people = @user.people
  end

  def new
    @user = User.find(params[:user_id])
    @person = Person.new
  end

  def create
    @user = User.find(params[:user_id])
    @person = Person.new(person_params)

    if @person.save
      redirect_to [@user, @person]
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:user_id])
    @person = @user.people.find(params[:id])

    if @person.update(person_params)
      redirect_to [@user, @person]
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @person = @user.people.find(params[:id])
  end

  def show
    @user = User.find(params[:user_id])
    @person = @user.people.find(params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @person = @user.people.find(params[:id])
    @person.destroy

    redirect_to user_people_path(@user)
  end

  def change_teams
    @user = User.find(params[:user_id])
    @person = @user.people.find(params[:id])
    @teams = @user.teams.where.not(id: @person.team_ids);
  end

  def add_to_team
    add_team_member(params[:team_id], params[:id])

    redirect_to :change_teams_user_person
  end

  def remove_from_team
    remove_team_member(params[:team_id], params[:id])

    redirect_to :change_teams_user_person
  end

  private
    def person_params
      params.require(:person).permit(:first_name, :last_name, :phone_number, :email, :birth_date, :linkedin_url, :image).merge(user_id: current_user.id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < OwnershipController
  include ChangeTeamMembers

  def index
    @user = User.find(params[:user_id])
    @teams = @user.teams
  end

  def new
    @user = User.find(params[:user_id])
    @team = Team.new
  end

  def create
    @user = User.find(params[:user_id])
    @team = Team.new(team_params)

    if @team.save
      redirect_to [current_user, @team]
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:user_id])
    @team = @user.teams.find(params[:id])

    if @team.update(team_params)
      redirect_to [@user, @team]
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @team = @user.teams.find(params[:id])
  end

  def show
    @user = User.find(params[:user_id])
    @team = @user.teams.find(params[:id])
    @members = @team.people
  end

  def destroy
    @user = User.find(params[:user_id])
    @team = @user.teams.find(params[:id])
    @team.destroy

    redirect_to user_teams_path(@user)
  end

  def change_people
    @user = User.find(params[:user_id])
    @team = @user.teams.find(params[:id])
    @people = @user.people.where.not(id: @team.person_ids);
  end

  def add_person
    add_team_member(params[:id], params[:person_id])

    redirect_to :change_people_user_team
  end

  def remove_person
    remove_team_member(params[:id], params[:person_id])

    redirect_to :change_people_user_team
  end

  private
    def team_params
      params.require(:team).permit(:name).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @teams = @user.teams.includes(:people)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User removed."
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = 'Human Resources'

    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_admin_footer.html.erb
<ul class="list-inline">
  <li><%= link_to 'Back to User', user_path(@user) %></li>
</ul>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Administration", new_admin_session_path %></li>
      <li><%= link_to "About",   pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Human Resources', home_path, class: "navbar-brand" %>
      <div class="nav navbar-right" >
        <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
            <li><a href="#">Welcome, administrator</a></li>
            <li><%= link_to 'Manage Users', users_path %></li>
            <li><%= link_to 'Log out', destroy_admin_session_path, :method => :delete %></li>
          <% elsif user_signed_in? %>
            <li><%= link_to "Welcome, #{current_user.email}", edit_user_registration_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">Manage</a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Manage People', user_people_path(current_user) %></li>
                <li><%= link_to 'Manage Teams', user_teams_path(current_user) %></li>
              </ul>
            </li>
            <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_team_listing.html.erb
<h3>Your Teams</h3>
<h2>Click to display members</h2>
<div class="list-group" style="width:30%">
  <% @teams.each do |team| %>
    <a class="list-group-item" data-toggle="collapse" data-target="#team<%=team.id%>">
      <%= team.name %>
    </a>
    <ul class="nav nav-list collapse" id="team<%=team.id%>">
      <% team.people.each do |member| %>
        <li><%= link_to member.name, user_person_path(current_user, member) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/pages/_user_listing.html.erb
<h3>List of Registered Users</h3>
<div class="list-group" style="width:30%">
  <% @users.each do |user| %>
    <%= link_to user.email, user_path(user),  class: 'list-group-item' %>
  <% end %>
</div>

app/views/pages/about.html.erb
<h1>Human Resources</h1>
<h2>About page</h2>

A very simple database-backed website for managing data on people and teams

app/views/pages/contact.html.erb
<h1>Human Resources</h1>
<h2>Contact</h2>

<h3>Site Author</h3>
<strong>Carlos Brito</strong><br/>
cfabrito@gmail.com

app/views/pages/index.html.erb
<div class="center hero-unit">
  <%= image_tag "logo.png" %>
  <h1>Welcome to Human Resources</h1>

  <h2 class="center">
    <% if user_signed_in? %>
      To start managing your teams click on the top-left links
    <% elsif admin_signed_in? %>
      Administration
    <% else %>
      To start using this application please <%= link_to 'Log in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>.
    <% end %>
  </h2>
</div>

<% if admin_signed_in? %>
  <%= render 'user_listing' %>
<% elsif user_signed_in? %>
  <%= render 'team_listing' %>
<% end %>

app/views/people/_form.html.erb
<%= form_for [@user, @person] do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prevented
      this person from being recorded:</h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :birth_date %><br>
    <%= f.date_field :birth_date %>
  </p>

  <p>
    <%= f.label :linkedin_url %><br>
    <%= f.url_field :linkedin_url %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/people/change_teams.html.erb
<% provide(:title, "Altering teams for #{@person.name}") %>
<h1> <%= @person.name %></h1>
<h2> Adding/Removing from Teams </h2>
<h3>Currently belongs to:</h3>
<dl class="dl-horizontal">
    <% @person.teams.each do |team| %>
      <dt><%= link_to team.name, user_team_path(@user, team) %></dt>
      <dd><%= link_to 'Remove', remove_from_team_user_person_path(@user, @person.id, team.id), method: :delete %></dd>
    <% end %>
  </dl>
<p>
<h3>Available teams are:</h3>
  <dl class="dl-horizontal">
    <% @teams.each do |team| %>
      <dt><%= link_to team.name, user_team_path(@user, team) %></dt>
      <dd><%= link_to 'Add', add_to_team_user_person_path(@user, @person.id, team), method: :post %></dd>
    <% end %>
  </dl>
</p>

<ul class="list-inline">
  <li><%= link_to "Back to Show", user_person_path(@user, @person) %></li>
  <li><%= link_to "Back to List", user_people_path %></li>
</ul>

app/views/people/edit.html.erb
<% provide(:title, "Editing #{@person.name}") %>
<h1> <%= @person.name %> </h1>
<h2> Editing personal information </h2>

<%= render 'form' %>

<ul class="list-inline">
  <li><%= link_to "Back to Show", user_person_path(@user, @person) %></li>
  <li><%= link_to "Back to List", user_people_path %></li>
</ul>

app/views/people/index.html.erb
<% provide(:title, 'Person Listing') %>
<h1>Person Listing</h1>
<h2>Click for details</h2>
<%= link_to "Add new entry", new_user_person_path(@user) %>
<div class="list-group" style="width:30%">
  <% @people.each do |person| %>
    <%= link_to person.name, user_person_path(@user, person), class: "list-group-item" %>
  <% end %>
</div>
<% if admin_signed_in? %>
  <%= render 'layouts/admin_footer' %>
<% end %>

app/views/people/new.html.erb
<% provide(:title, 'New Person') %>
<h1> New Person </h1>
<h2> Add a new Person entry </h2>
<%= render 'form' %>
<ul class="list-inline">
  <li><%= link_to "Back to List", user_people_path %></li>
</ul>

app/views/people/show.html.erb
<% provide(:title, @person.name) %>
<h1> <%= @person.name %> </h1>
<% if @person.image.blank? %>
  <%= image_tag 'image_not_available.jpg', style:'width:150px;height:150px' %>
<% else %>
  <img src="<%= @person.image %>" alt="<%= @person.name %>" style="width:150px;height:150px">
<% end %>
<h2> Personal Information </h2>

<dl class="dl-horizontal">
    <dt>Fist Name</dt>
  <dd><%= @person.first_name %></dd>

    <dt>Last Name</dt>
  <dd><%= @person.last_name %></dd>

    <dt>Phone Number</dt>
  <dd><%= @person.phone_number %></dd>

    <dt>Email Address</dt>
  <dd><%= @person.email %></dd>

    <dt>Date of Birth</dt>
  <dd><%= @person.birth_date %></dd>

  <dt>LinkedIn</dt>
    <dd><%= @person.linkedin_url %></dd>

  <dt>Belongs to teams: </dt>
    <dd>
      <ul class="list-unstyled">
        <% @person.teams.each do |team| %>
        <li> <%= link_to team.name, user_team_path(@user, team) %> </li>
        <% end %>
      </ul>
    </dd>
</dl>
<ul class="list-inline">
  <li><%= link_to 'Back to List', user_people_path(@user) %></li>
  <li><%= link_to 'Edit Fields',  edit_user_person_path(@user,@person) %></li>
  <li><%= link_to 'Change Teams', change_teams_user_person_path(@user,@person) %></li>
  <li><%= link_to 'Delete', user_person_path(@user,@person), method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>

app/views/users/_user_listing.html.erb
<div class="list-group" style="width:30%">
  <% @users.each do |user| %>
    <%= link_to user.email, user_path(user),  class: 'list-group-item' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<h2>Currently registered users</h2>
<%= render 'user_listing' %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<h2>User Details</h2>
<dl class="dl-horizontal">
  <dt>Email Address</dt>
  <dd><%= @user.email %></dd>
</dl>
<ul class="list-inline">
  <li><%= link_to 'Back to List', users_path %></li>
  <li><%= link_to 'Show teams',  user_teams_path(@user) %></li>
  <li><%= link_to 'Show people', user_people_path(@user) %></li>
  <li><%= link_to "Remove", user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %></li>
</ul>